# API keys for embedding models and vector databases
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"
COHERE_API_KEY = "YOUR_COHERE_API_KEY"
PINECONE_API_KEY = "YOUR_PINECONE_API_KEY"
WEAVIATE_API_KEY = "YOUR_WEAVIATE_API_KEY"
QDRANT_API_KEY = "YOUR_QDRANT_API_KEY"
CHROMA_DB_PATH = "YOUR_CHROMA_DB_PATH" # For local ChromaDB